### ISSUE TITLE
Instructions for installing Joern v. 0.2.5

### ISSUE THREAD

**Issue by Manas-Embold** [bbowman410/VGraph#1]
Hi @bbowman410 

Can you share steps to install this particular version of joern. (v. 0.2.5)
Also, how to setup joern-parse

Many Thanks

**Comment by bbowman410** [comment]
Hello!

You should be able to install the older, unmaintained version of joern from this repository: https://github.com/octopus-platform/joern.  If you look at tags you will see the 0.2.5 version I used.  The documentation for installation can be found here: https://joern.readthedocs.io/en/latest/.  After building & installing joern, the joern-parse tool should just work.  As far as I remember it does not need any special setup.  It's a simple command line tool which allows you to pass it a file and it will parse the content with joern.  This side-steps the neo4j database, so you may be able to skip that portion of the installation guide as well.

**Comment by Manas-Embold** [comment]
Thanks
Installation using https://joern.readthedocs.io/en/dev/installation.html helped.
This bundle included joern-parse
