### ISSUE TITLE
How to derive optimum values of Threshold

### ISSUE THREAD

**Issue by Manas-Embold** [bbowman410/VGraph#4]
Hi @bbowman410 

I wish to derive at optimum value for the thresholds.
The paper talks about looking at some cumulative distribution function: "we compute the Cumulative Distribution Function (CDF) of the context triplet scores, and the positive triplet scores, for each VGRAPH against all other functions in the database." 

Is it done using plotting "cvg_score", "pvg_score" for target db created on source repos in repos.config ? or something else.
OR
Is it done over Source Repositories (repos.config) only? We don't have to involve target repos (on which we run find_vulns.py) for determining thresholds right ?

I would request some more explanation around that.
Is there any particular script which would plot the CDF so that we can check on optimum value of thresholds on the plotted graph ?

**Comment by Manas-Embold** [comment]
**Another Question:**

Consider Line number 7 of Algorithm in paper:
![image](https://user-images.githubusercontent.com/61409155/108059219-2e990280-707b-11eb-9555-f5db021e3d34.png)
It checks "scoreN < scoreP"

However, tf i look at decision function in find_vuls.py
![image](https://user-images.githubusercontent.com/61409155/108059377-6dc75380-707b-11eb-9b64-ebc49b3abc1b.png)
The function compares "nvg_score < NVG_THRESH" instead of "nvg_score < pvg_score"

**Comment by bbowman410** [comment]
Hi there,

Regarding your second question, that `find_vulns.py` script appears to be a little out of date.  The `eval_vgraph.py` is the script that runs the code that generated most of the number for the paper.  The decision function in that script matches the paper.

Regarding the first question on threshold determination: 

The CDF is a standard statistical analysis technique for analyzing a data distribution.  There are explanations on the web for computing or plotting the CDF in Excel or Python or probably any data analysis software you want.

I wanted to choose the threshold value based only on the training data so as to not mix any training/testing data.  So basically I just computed the cvg_score and pvg_score of every VGraph against every function (except for the one the was originally used to generate the VGraph).  The assumption here is that the vast majority of other functions in our VGraph database are unlikely to be code clones of each other.  When we analyze the results (via a CDF, or any other statistical measure), we can see that in fact the vast majority of other functions do match very low (as expected).  In the paper, we chose a threshold where 99% of the functions received a score lower than the particular value (indicated by the red dashed line in the paper).

**Comment by Manas-Embold** [comment]
Many Thanks
That detailed explanation cleared the issue.

**Comment by Manas-Embold** [comment]
May i ask,
what is the purpose of cleaning target db here: https://github.com/bbowman410/VGraph/blob/ddeaf07e4f5864a1788d62b8a7893d415f44a525/evaluate_vgraph.py#L660

Looks like some sort of filtering like choosing functions in target db which are only there in source or something else ?

Also we pass func_list of source db here : https://github.com/bbowman410/VGraph/blob/ddeaf07e4f5864a1788d62b8a7893d415f44a525/evaluate_vgraph.py#L659

while loading target db but in find_vulns.py, target db is loaded fithout passing source db function list.
Any particular reasons ?

**Comment by bbowman410** [comment]
Regarding first: There are a few instances where a VGraph fails to be built for a particular function (e.g., vulnerable, patched functions don't actually contain any change in code).  So here we are checking to make sure that we actually have a VGraph generated for a particular function. 

Regarding the second:  The `find_vulns.py` was used when looking for new bugs in new code repositories with no ground truth, so we simply compared against all functions in the codebase.  The `eval_vgraph.py` script is used to run experiments and internally evaluate how well our VGraph detects vulnerable code clones based on some known ground truth.  We pass a list of functions for things we know we have VGraphs for so we can control for that in the experiments.  So this question is actually similar to your first.  The goal of this script is to evaluate the VGraph data structure, so we are trying to filter out any noise that may pollute our results.

**Comment by Manas-Embold** [comment]
Do you recommend the filtering should happen for target db for find_vulns.py as well ?  That won't make sense right ?
I mean when ground truth is not available

**Comment by bbowman410** [comment]
Correct that would not make sense.  The only reason for the down-select was for controlling the experiment.  If your goal is to find vulnerable clones in new functions from new projects you certainly don't want to require that they have same function name and come from the same project.
