### ISSUE TITLE
`manual_lables.txt` does not exist

### ISSUE THREAD

**Issue by gaow0007** [bbowman410/VGraph#5]
Hi， 
Thanks for sharing your code. I encounter a issue. 
When I run evaluate_vgraph.py. The error comes out.
**No such file or directory: './manual_labels.txt'.**
Could you supply a way to obtain `./manual_labels.txt`

**Comment by bbowman410** [comment]
Hello,

The manual_labels.txt is exactly what it sounds like - a list of manually defined labels for some of the cross-CVE clones that couldn't be labeled automatically.  This means it is highly coupled to the code repositories you are testing.  If you are testing new repositories, or even the same repositories but with new CVEs, this list may require some tuning.  I have attached the list of manual labels I used for the experiments from the paper.

[manual_labels.txt](https://github.com/bbowman410/VGraph/files/6249515/manual_labels.txt)

**Comment by gaow0007** [comment]
thank you for you reply. 

Best.
